server:
  port: 8761

eureka:
  dashboard:
    path: /dashboard
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
server:
  port: 8762
spring:
  profiles: eureka1    
eureka:
  dashboard:
    path: /dashboard
  instance:
    hostname: eureka1
    leaseRenewalIntervalInSeconds: 3
  client:
 
    serviceUrl:
      defaultZone: http://eureka2:8763/eureka/

---
server:
  port: 8763
spring:
  profiles: eureka2  
eureka:
  dashboard:
    path: /dashboard
  instance:
    hostname: eureka2
    leaseRenewalIntervalInSeconds: 3
  client:

    serviceUrl:
      defaultZone: http://eureka1:8762/eureka/
    